export const MAIN_STATUS_TYPES = {
  WAITING: 'WAITING',
  DICTATING: 'DICTATING',
  COMMAND_PROCESSED: 'COMMAND_PROCESSED',
  STARTING_TIMER: 'STARTING_TIMER'
};

export const TIMER_STATUS_TYPES = {
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED'
};
